apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaintpharsha/Devops-ITD-May-2023.git
    targetRevision: main
    path: Kubernetes/argo/yamls
  destination:
    server: https://13.201.8.19:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
