apiVersion: batch/v1
kind: Jobs
metadata:
    name: my-job
spec:
    template:
      spec: 
         containers: 
         - name: busybox 
           image: busybox
           command: ["echo", "JOBS"]
           restartPolicy: Never 
